# The following is an example of a custom-tasks.yaml for adding custom webapp configuration files
---
- name: configure nonstandard files
  template:
    src: "{{ playbook_dir }}/templates/{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0775"
  become: yes
  become_user: "{{ polaris_install_user }}"
  with_items:
  - {
      src: "configuration.ts.j2",
      dest: "{{ nodejs_app_service_install_app_home }}/dist/config/configuration.js"
   }
